/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsSessionsRouteImport } from './routes/reports.sessions'
import { Route as ReportsTablesRouteImport } from './routes/reports.tables'
import { Route as ReportsSessionsSessionIdRouteImport } from './routes/reports.sessions.$sessionId'
import { Route as ReportsTablesTableIdRouteImport } from './routes/reports.tables.$tableId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSessionsRoute = ReportsSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsTablesRoute = ReportsTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSessionsSessionIdRoute =
  ReportsSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => ReportsSessionsRoute,
  } as any)
const ReportsTablesTableIdRoute = ReportsTablesTableIdRouteImport.update({
  id: '/$tableId',
  path: '/$tableId',
  getParentRoute: () => ReportsTablesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reports/sessions': typeof ReportsSessionsRouteWithChildren
  '/reports/tables': typeof ReportsTablesRouteWithChildren
  '/reports/': typeof ReportsIndexRoute
  '/reports/sessions/$sessionId': typeof ReportsSessionsSessionIdRoute
  '/reports/tables/$tableId': typeof ReportsTablesTableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports/sessions': typeof ReportsSessionsRouteWithChildren
  '/reports/tables': typeof ReportsTablesRouteWithChildren
  '/reports': typeof ReportsIndexRoute
  '/reports/sessions/$sessionId': typeof ReportsSessionsSessionIdRoute
  '/reports/tables/$tableId': typeof ReportsTablesTableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reports/sessions': typeof ReportsSessionsRouteWithChildren
  '/reports/tables': typeof ReportsTablesRouteWithChildren
  '/reports/': typeof ReportsIndexRoute
  '/reports/sessions/$sessionId': typeof ReportsSessionsSessionIdRoute
  '/reports/tables/$tableId': typeof ReportsTablesTableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports'
    | '/reports/sessions'
    | '/reports/tables'
    | '/reports/'
    | '/reports/sessions/$sessionId'
    | '/reports/tables/$tableId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reports/sessions'
    | '/reports/tables'
    | '/reports'
    | '/reports/sessions/$sessionId'
    | '/reports/tables/$tableId'
  id:
    | '__root__'
    | '/'
    | '/reports'
    | '/reports/sessions'
    | '/reports/tables'
    | '/reports/'
    | '/reports/sessions/$sessionId'
    | '/reports/tables/$tableId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsRoute: typeof ReportsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/sessions': {
      id: '/reports/sessions'
      path: '/sessions'
      fullPath: '/reports/sessions'
      preLoaderRoute: typeof ReportsSessionsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/tables': {
      id: '/reports/tables'
      path: '/tables'
      fullPath: '/reports/tables'
      preLoaderRoute: typeof ReportsTablesRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/sessions/$sessionId': {
      id: '/reports/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/reports/sessions/$sessionId'
      preLoaderRoute: typeof ReportsSessionsSessionIdRouteImport
      parentRoute: typeof ReportsSessionsRoute
    }
    '/reports/tables/$tableId': {
      id: '/reports/tables/$tableId'
      path: '/$tableId'
      fullPath: '/reports/tables/$tableId'
      preLoaderRoute: typeof ReportsTablesTableIdRouteImport
      parentRoute: typeof ReportsTablesRoute
    }
  }
}

interface ReportsSessionsRouteChildren {
  ReportsSessionsSessionIdRoute: typeof ReportsSessionsSessionIdRoute
}

const ReportsSessionsRouteChildren: ReportsSessionsRouteChildren = {
  ReportsSessionsSessionIdRoute: ReportsSessionsSessionIdRoute,
}

const ReportsSessionsRouteWithChildren = ReportsSessionsRoute._addFileChildren(
  ReportsSessionsRouteChildren,
)

interface ReportsTablesRouteChildren {
  ReportsTablesTableIdRoute: typeof ReportsTablesTableIdRoute
}

const ReportsTablesRouteChildren: ReportsTablesRouteChildren = {
  ReportsTablesTableIdRoute: ReportsTablesTableIdRoute,
}

const ReportsTablesRouteWithChildren = ReportsTablesRoute._addFileChildren(
  ReportsTablesRouteChildren,
)

interface ReportsRouteChildren {
  ReportsSessionsRoute: typeof ReportsSessionsRouteWithChildren
  ReportsTablesRoute: typeof ReportsTablesRouteWithChildren
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsSessionsRoute: ReportsSessionsRouteWithChildren,
  ReportsTablesRoute: ReportsTablesRouteWithChildren,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsRoute: ReportsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
